v2

diff --git a/.github/workflows/npm-release.yml b/.github/workflows/npm-release.yml
--- a/.github/workflows/npm-release.yml
+++ b/.github/workflows/npm-release.yml
@@ -6,14 +6,14 @@
 #       id-token: write
 #     uses: szikszail/workflows/.github/workflows/npm-release.yml@main
 #     secrets:
-#       npm_token: ${{ secrets.npm_token }}    
+#       npm_token: ${{ secrets.npm_token }}
 name: Publishing latest version of the package to NPM
 on:
   workflow_call:
     inputs:
       dist_folder:
         required: false
-        default: './dist'
+        default: "./dist"
         type: string
     secrets:
       npm_token:
@@ -24,9 +24,9 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
       - name: Setting up Node.js
-        uses: actions/setup-node@v4
+        uses: actions/setup-node@v6
         with:
           node-version: lts/*
           registry-url: https://registry.npmjs.org/
@@ -43,9 +43,9 @@ jobs:
       id-token: write
     steps:
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
       - name: Setting up Node.js
-        uses: actions/setup-node@v4
+        uses: actions/setup-node@v6
         with:
           node-version: lts/*
           registry-url: https://registry.npmjs.org/
@@ -56,16 +56,12 @@ jobs:
       - name: Release
         run: npm publish --provenance --access public .
         working-directory: ${{ inputs.dist_folder }}
-        env:
-          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
       - name: Unpublishing BETA versions
         run: |
           cn=$(cat package.json | grep name | cut -d '"' -f 4)
           cv=$(cat package.json | grep version | cut -d '"' -f 4)
           betas=$(npm info $cn versions --json | grep $cv-beta | cut -d '"' -f 2)
-          for v in $betas; do 
-            npm deprecate $cn@$v "Use latest version: $cv!" || echo "Could not deprecate: $cv!"; 
+          for v in $betas; do
+            npm deprecate $cn@$v "Use latest version: $cv!" || echo "Could not deprecate: $cv!";
           done
         working-directory: ${{ inputs.dist_folder }}
-        env:
-          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
