Update npm-release.yml

diff --git a/.github/workflows/npm-release.yml b/.github/workflows/npm-release.yml
--- a/.github/workflows/npm-release.yml
+++ b/.github/workflows/npm-release.yml
@@ -50,3 +50,14 @@ jobs:
         working-directory: ./dist
         env:
           NODE_AUTH_TOKEN: ${{secrets.npm_token}}
+      - name: Unpublishing BETA versions
+        run: |
+          cn=$(cat package.json | grep name | cut -d '"' -f 4)
+          cv=$(cat package.json | grep version | cut -d '"' -f 4)
+          betas=$(npm info $cn versions --json | grep $cv-beta | cut -d '"' -f 2)
+          for v in $betas; do 
+            npm deprecate $cn@$v "Use latest version: $cv!" || echo "Could not deprecate: $cv!"; 
+          done
+        working-directory: ./dist
+        env:
+          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
